// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetOccurrenceParams is parameters of getOccurrence operation.
type GetOccurrenceParams struct {
	Ref string
}

func unpackGetOccurrenceParams(packed middleware.Parameters) (params GetOccurrenceParams) {
	{
		key := middleware.ParameterKey{
			Name: "ref",
			In:   "path",
		}
		params.Ref = packed[key].(string)
	}
	return params
}

func decodeGetOccurrenceParams(args [1]string, argsEscaped bool, r *http.Request) (params GetOccurrenceParams, _ error) {
	// Decode path: ref.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "ref",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Ref = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ref",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetRelatedLogsParams is parameters of getRelatedLogs operation.
type GetRelatedLogsParams struct {
	Ref string
}

func unpackGetRelatedLogsParams(packed middleware.Parameters) (params GetRelatedLogsParams) {
	{
		key := middleware.ParameterKey{
			Name: "ref",
			In:   "path",
		}
		params.Ref = packed[key].(string)
	}
	return params
}

func decodeGetRelatedLogsParams(args [1]string, argsEscaped bool, r *http.Request) (params GetRelatedLogsParams, _ error) {
	// Decode path: ref.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "ref",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Ref = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ref",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetTraceParams is parameters of getTrace operation.
type GetTraceParams struct {
	TraceId string
}

func unpackGetTraceParams(packed middleware.Parameters) (params GetTraceParams) {
	{
		key := middleware.ParameterKey{
			Name: "traceId",
			In:   "path",
		}
		params.TraceId = packed[key].(string)
	}
	return params
}

func decodeGetTraceParams(args [1]string, argsEscaped bool, r *http.Request) (params GetTraceParams, _ error) {
	// Decode path: traceId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "traceId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.TraceId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "traceId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
