// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/uri"
)

func encodeGetCapabilitiesResponse(response *CapabilitiesHeaders, w http.ResponseWriter) error {
	if err := func() error {
		if err := response.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return errors.Wrap(err, "validate")
	}
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("Access-Control-Expose-Headers", "X-Errotel-Cache,X-Errotel-Cache-Age-Ms,X-Errotel-Fetched-At")
	// Encoding response headers.
	{
		h := uri.NewHeaderEncoder(w.Header())
		// Encode "X-Errotel-Cache" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Cache",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelCache.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Cache header")
			}
		}
		// Encode "X-Errotel-Cache-Age-Ms" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Cache-Age-Ms",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelCacheAgeMs.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Cache-Age-Ms header")
			}
		}
		// Encode "X-Errotel-Fetched-At" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Fetched-At",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelFetchedAt.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Fetched-At header")
			}
		}
	}
	w.WriteHeader(200)

	e := new(jx.Encoder)
	response.Response.Encode(e)
	if _, err := e.WriteTo(w); err != nil {
		return errors.Wrap(err, "write")
	}

	return nil
}

func encodeGetFacetsResponse(response *FacetResponseHeaders, w http.ResponseWriter) error {
	if err := func() error {
		if err := response.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return errors.Wrap(err, "validate")
	}
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("Access-Control-Expose-Headers", "X-Errotel-Cache,X-Errotel-Cache-Age-Ms,X-Errotel-Fetched-At")
	// Encoding response headers.
	{
		h := uri.NewHeaderEncoder(w.Header())
		// Encode "X-Errotel-Cache" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Cache",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelCache.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Cache header")
			}
		}
		// Encode "X-Errotel-Cache-Age-Ms" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Cache-Age-Ms",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelCacheAgeMs.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Cache-Age-Ms header")
			}
		}
		// Encode "X-Errotel-Fetched-At" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Fetched-At",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelFetchedAt.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Fetched-At header")
			}
		}
	}
	w.WriteHeader(200)

	e := new(jx.Encoder)
	response.Response.Encode(e)
	if _, err := e.WriteTo(w); err != nil {
		return errors.Wrap(err, "write")
	}

	return nil
}

func encodeGetHistogramResponse(response *HistogramResponseHeaders, w http.ResponseWriter) error {
	if err := func() error {
		if err := response.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return errors.Wrap(err, "validate")
	}
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("Access-Control-Expose-Headers", "X-Errotel-Cache,X-Errotel-Cache-Age-Ms,X-Errotel-Fetched-At")
	// Encoding response headers.
	{
		h := uri.NewHeaderEncoder(w.Header())
		// Encode "X-Errotel-Cache" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Cache",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelCache.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Cache header")
			}
		}
		// Encode "X-Errotel-Cache-Age-Ms" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Cache-Age-Ms",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelCacheAgeMs.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Cache-Age-Ms header")
			}
		}
		// Encode "X-Errotel-Fetched-At" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Fetched-At",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelFetchedAt.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Fetched-At header")
			}
		}
	}
	w.WriteHeader(200)

	e := new(jx.Encoder)
	response.Response.Encode(e)
	if _, err := e.WriteTo(w); err != nil {
		return errors.Wrap(err, "write")
	}

	return nil
}

func encodeGetOccurrenceResponse(response *OccurrenceDetailHeaders, w http.ResponseWriter) error {
	if err := func() error {
		if err := response.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return errors.Wrap(err, "validate")
	}
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("Access-Control-Expose-Headers", "X-Errotel-Cache,X-Errotel-Cache-Age-Ms,X-Errotel-Fetched-At")
	// Encoding response headers.
	{
		h := uri.NewHeaderEncoder(w.Header())
		// Encode "X-Errotel-Cache" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Cache",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelCache.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Cache header")
			}
		}
		// Encode "X-Errotel-Cache-Age-Ms" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Cache-Age-Ms",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelCacheAgeMs.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Cache-Age-Ms header")
			}
		}
		// Encode "X-Errotel-Fetched-At" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Fetched-At",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelFetchedAt.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Fetched-At header")
			}
		}
	}
	w.WriteHeader(200)

	e := new(jx.Encoder)
	response.Response.Encode(e)
	if _, err := e.WriteTo(w); err != nil {
		return errors.Wrap(err, "write")
	}

	return nil
}

func encodeGetRelatedLogsResponse(response *RelatedResponseHeaders, w http.ResponseWriter) error {
	if err := func() error {
		if err := response.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return errors.Wrap(err, "validate")
	}
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("Access-Control-Expose-Headers", "X-Errotel-Cache,X-Errotel-Cache-Age-Ms,X-Errotel-Fetched-At")
	// Encoding response headers.
	{
		h := uri.NewHeaderEncoder(w.Header())
		// Encode "X-Errotel-Cache" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Cache",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelCache.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Cache header")
			}
		}
		// Encode "X-Errotel-Cache-Age-Ms" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Cache-Age-Ms",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelCacheAgeMs.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Cache-Age-Ms header")
			}
		}
		// Encode "X-Errotel-Fetched-At" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Fetched-At",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelFetchedAt.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Fetched-At header")
			}
		}
	}
	w.WriteHeader(200)

	e := new(jx.Encoder)
	response.Response.Encode(e)
	if _, err := e.WriteTo(w); err != nil {
		return errors.Wrap(err, "write")
	}

	return nil
}

func encodeGetTraceResponse(response *TraceResponseHeaders, w http.ResponseWriter) error {
	if err := func() error {
		if err := response.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return errors.Wrap(err, "validate")
	}
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("Access-Control-Expose-Headers", "X-Errotel-Cache,X-Errotel-Cache-Age-Ms,X-Errotel-Fetched-At")
	// Encoding response headers.
	{
		h := uri.NewHeaderEncoder(w.Header())
		// Encode "X-Errotel-Cache" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Cache",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelCache.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Cache header")
			}
		}
		// Encode "X-Errotel-Cache-Age-Ms" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Cache-Age-Ms",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelCacheAgeMs.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Cache-Age-Ms header")
			}
		}
		// Encode "X-Errotel-Fetched-At" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Fetched-At",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelFetchedAt.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Fetched-At header")
			}
		}
	}
	w.WriteHeader(200)

	e := new(jx.Encoder)
	response.Response.Encode(e)
	if _, err := e.WriteTo(w); err != nil {
		return errors.Wrap(err, "write")
	}

	return nil
}

func encodeInvestigateResponse(response *InvestigationResponseHeaders, w http.ResponseWriter) error {
	if err := func() error {
		if err := response.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return errors.Wrap(err, "validate")
	}
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("Access-Control-Expose-Headers", "X-Errotel-Cache,X-Errotel-Cache-Age-Ms,X-Errotel-Fetched-At")
	// Encoding response headers.
	{
		h := uri.NewHeaderEncoder(w.Header())
		// Encode "X-Errotel-Cache" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Cache",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelCache.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Cache header")
			}
		}
		// Encode "X-Errotel-Cache-Age-Ms" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Cache-Age-Ms",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelCacheAgeMs.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Cache-Age-Ms header")
			}
		}
		// Encode "X-Errotel-Fetched-At" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Fetched-At",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelFetchedAt.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Fetched-At header")
			}
		}
	}
	w.WriteHeader(200)

	e := new(jx.Encoder)
	response.Response.Encode(e)
	if _, err := e.WriteTo(w); err != nil {
		return errors.Wrap(err, "write")
	}

	return nil
}

func encodePrepareAlertResponse(response *AlertConfigurationHeaders, w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("Access-Control-Expose-Headers", "X-Errotel-Cache,X-Errotel-Cache-Age-Ms,X-Errotel-Fetched-At")
	// Encoding response headers.
	{
		h := uri.NewHeaderEncoder(w.Header())
		// Encode "X-Errotel-Cache" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Cache",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelCache.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Cache header")
			}
		}
		// Encode "X-Errotel-Cache-Age-Ms" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Cache-Age-Ms",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelCacheAgeMs.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Cache-Age-Ms header")
			}
		}
		// Encode "X-Errotel-Fetched-At" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Fetched-At",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelFetchedAt.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Fetched-At header")
			}
		}
	}
	w.WriteHeader(200)

	e := new(jx.Encoder)
	response.Response.Encode(e)
	if _, err := e.WriteTo(w); err != nil {
		return errors.Wrap(err, "write")
	}

	return nil
}

func encodeSearchOccurrencesResponse(response *SearchResponseHeaders, w http.ResponseWriter) error {
	if err := func() error {
		if err := response.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return errors.Wrap(err, "validate")
	}
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("Access-Control-Expose-Headers", "X-Errotel-Cache,X-Errotel-Cache-Age-Ms,X-Errotel-Fetched-At")
	// Encoding response headers.
	{
		h := uri.NewHeaderEncoder(w.Header())
		// Encode "X-Errotel-Cache" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Cache",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelCache.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Cache header")
			}
		}
		// Encode "X-Errotel-Cache-Age-Ms" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Cache-Age-Ms",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelCacheAgeMs.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Cache-Age-Ms header")
			}
		}
		// Encode "X-Errotel-Fetched-At" header.
		{
			cfg := uri.HeaderParameterEncodingConfig{
				Name:    "X-Errotel-Fetched-At",
				Explode: false,
			}
			if err := h.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := response.XErrotelFetchedAt.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode X-Errotel-Fetched-At header")
			}
		}
	}
	w.WriteHeader(200)

	e := new(jx.Encoder)
	response.Response.Encode(e)
	if _, err := e.WriteTo(w); err != nil {
		return errors.Wrap(err, "write")
	}

	return nil
}

func encodeErrorResponse(response *ApiErrorStatusCode, w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	code := response.StatusCode
	if code == 0 {
		// Set default status code.
		code = http.StatusOK
	}
	w.WriteHeader(code)

	e := new(jx.Encoder)
	response.Response.Encode(e)
	if _, err := e.WriteTo(w); err != nil {
		return errors.Wrap(err, "write")
	}

	if code >= http.StatusInternalServerError {
		return errors.Wrapf(ht.ErrInternalServerErrorResponse, "code: %d, message: %s", code, http.StatusText(code))
	}
	return nil

}
