// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetCapabilities implements getCapabilities operation.
	//
	// GET /api/v1/capabilities
	GetCapabilities(ctx context.Context) (*CapabilitiesHeaders, error)
	// GetFacets implements getFacets operation.
	//
	// POST /api/v1/facets
	GetFacets(ctx context.Context, req *FacetRequest) (*FacetResponseHeaders, error)
	// GetHistogram implements getHistogram operation.
	//
	// POST /api/v1/occurrences/histogram
	GetHistogram(ctx context.Context, req *OccurrenceSearch) (*HistogramResponseHeaders, error)
	// GetOccurrence implements getOccurrence operation.
	//
	// GET /api/v1/occurrences/{ref}
	GetOccurrence(ctx context.Context, params GetOccurrenceParams) (*OccurrenceDetailHeaders, error)
	// GetRelatedLogs implements getRelatedLogs operation.
	//
	// POST /api/v1/occurrences/{ref}/related
	GetRelatedLogs(ctx context.Context, req *RelatedRequest, params GetRelatedLogsParams) (*RelatedResponseHeaders, error)
	// GetTrace implements getTrace operation.
	//
	// GET /api/v1/traces/{traceId}
	GetTrace(ctx context.Context, params GetTraceParams) (*TraceResponseHeaders, error)
	// Investigate implements investigate operation.
	//
	// POST /api/v1/investigate
	Investigate(ctx context.Context, req *InvestigationRequest) (*InvestigationResponseHeaders, error)
	// PrepareAlert implements prepareAlert operation.
	//
	// POST /api/v1/alerts/prepare
	PrepareAlert(ctx context.Context, req *AlertPreparation) (*AlertConfigurationHeaders, error)
	// SearchOccurrences implements searchOccurrences operation.
	//
	// POST /api/v1/occurrences/search
	SearchOccurrences(ctx context.Context, req *OccurrenceSearch) (*SearchResponseHeaders, error)
	// NewError creates *ApiErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ApiErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
