// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	GetCapabilitiesOperation   OperationName = "GetCapabilities"
	GetFacetsOperation         OperationName = "GetFacets"
	GetHistogramOperation      OperationName = "GetHistogram"
	GetOccurrenceOperation     OperationName = "GetOccurrence"
	GetRelatedLogsOperation    OperationName = "GetRelatedLogs"
	GetTraceOperation          OperationName = "GetTrace"
	InvestigateOperation       OperationName = "Investigate"
	PrepareAlertOperation      OperationName = "PrepareAlert"
	SearchOccurrencesOperation OperationName = "SearchOccurrences"
)
