// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetCapabilities implements getCapabilities operation.
//
// GET /api/v1/capabilities
func (UnimplementedHandler) GetCapabilities(ctx context.Context) (r *CapabilitiesHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFacets implements getFacets operation.
//
// POST /api/v1/facets
func (UnimplementedHandler) GetFacets(ctx context.Context, req *FacetRequest) (r *FacetResponseHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHistogram implements getHistogram operation.
//
// POST /api/v1/occurrences/histogram
func (UnimplementedHandler) GetHistogram(ctx context.Context, req *OccurrenceSearch) (r *HistogramResponseHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOccurrence implements getOccurrence operation.
//
// GET /api/v1/occurrences/{ref}
func (UnimplementedHandler) GetOccurrence(ctx context.Context, params GetOccurrenceParams) (r *OccurrenceDetailHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRelatedLogs implements getRelatedLogs operation.
//
// POST /api/v1/occurrences/{ref}/related
func (UnimplementedHandler) GetRelatedLogs(ctx context.Context, req *RelatedRequest, params GetRelatedLogsParams) (r *RelatedResponseHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTrace implements getTrace operation.
//
// GET /api/v1/traces/{traceId}
func (UnimplementedHandler) GetTrace(ctx context.Context, params GetTraceParams) (r *TraceResponseHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// Investigate implements investigate operation.
//
// POST /api/v1/investigate
func (UnimplementedHandler) Investigate(ctx context.Context, req *InvestigationRequest) (r *InvestigationResponseHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// PrepareAlert implements prepareAlert operation.
//
// POST /api/v1/alerts/prepare
func (UnimplementedHandler) PrepareAlert(ctx context.Context, req *AlertPreparation) (r *AlertConfigurationHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchOccurrences implements searchOccurrences operation.
//
// POST /api/v1/occurrences/search
func (UnimplementedHandler) SearchOccurrences(ctx context.Context, req *OccurrenceSearch) (r *SearchResponseHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ApiErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ApiErrorStatusCode) {
	r = new(ApiErrorStatusCode)
	return r
}
